//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceProgram.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisment()
        {
            this.Flight_Advertisment = new HashSet<Flight_Advertisment>();
        }
    
        public int Advertisment_ID { get; set; }
        public string Name { get; set; }
        public decimal Income { get; set; }
        public int AdvertisingAgent_ID { get; set; }
    
        public virtual AdvertisingAgent AdvertisingAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Advertisment> Flight_Advertisment { get; set; }
    }
}
