//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceProgram.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Crew_Employee = new HashSet<Crew_Employee>();
        }
    
        public int Employee_ID { get; set; }
        public string Name { get; set; }
        public int Role_ID { get; set; }
        public int Qualification_ID { get; set; }
        public Nullable<bool> visiblity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crew_Employee> Crew_Employee { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Role Role { get; set; }
    }
}
