//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceProgram.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Flight_Advertisment = new HashSet<Flight_Advertisment>();
        }
    
        public int Flight_ID { get; set; }
        public int Crew_ID { get; set; }
        public int Route_ID { get; set; }
        public int SpaceObject_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Advertisment> Flight_Advertisment { get; set; }
        public virtual Route Route { get; set; }
        public virtual SpaceObject SpaceObject { get; set; }
        public virtual Crew Crew { get; set; }
    }
}
