//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceProgram.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Advertisment
    {
        public int Flight_Advertisment_ID { get; set; }
        public int Flight_ID { get; set; }
        public int Advertisment_ID { get; set; }
    
        public virtual Advertisment Advertisment { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
